[package]
name = "mal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
regex = "1.11.1"
rustyline = "15.0.0"

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"

[[bin]]
name = "step1_read_print"
path = "step1_read_print.rs"
